title: AVAnnotate User Guidelines and Resources
description: These guidelines are for AVAnnotate user communities including scholars, information professionals, teachers, and the public.
theme: just-the-docs

url: https://avannotate.github.io/guidelines

aux_links: # remove if you don't want this link to appear on your pages
  AVAnnotate Website: https://av-annotate.org/
  Application: https://avannotate.netlify.app/
  Documentation: https://avannotate.github.io/documentation/
